# Generated by Django 2.1.5 on 2019-04-30 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LightStrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.BooleanField(default=True, verbose_name='light strip power')),
                ('brightness', models.IntegerField(default=128, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='brightness level')),
                ('current_profile', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='currently selected profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
